file(COPY "${REPO_DIR}/FindOpenVR.cmake" DESTINATION "${CGET_INSTALL_DIR}/lib/cmake")
CGET_GET_PACKAGE(openvr GITHUB ValveSoftware/openvr)

if(MSVC OR MINGW)
    if(CGET_ARCH MATCHES "x64")
        file(GLOB OPENVR_DLLS "${CGET_openvr_REPO_DIR}/bin/win64/*")   
        file(GLOB OPENVR_LIBS "${CGET_openvr_REPO_DIR}/lib/win64/*")                
    else()
        file(GLOB OPENVR_DLLS "${CGET_openvr_REPO_DIR}/bin/win32/*")
        file(GLOB OPENVR_LIBS "${CGET_openvr_REPO_DIR}/lib/win32/*")               
    endif()
    file(COPY ${OPENVR_DLLS} DESTINATION "${CGET_INSTALL_DIR}/bin")
    file(COPY ${OPENVR_LIBS} DESTINATION "${CGET_INSTALL_DIR}/lib")
endif()
file(GLOB OPENVR_HEADERS "${CGET_openvr_REPO_DIR}/headers/*")               
file(COPY ${OPENVR_HEADERS} DESTINATION "${CGET_INSTALL_DIR}/include")

set(ARGS_NO_FIND_PACKAGE OFF)