file(COPY "${REPO_DIR}/FindOpenVR.cmake" DESTINATION "${CGET_INSTALL_DIR}/lib/cmake")
CGET_GET_PACKAGE(openvr GITHUB ValveSoftware/openvr NO_FIND_PACKAGE)

if(MSVC OR MINGW)
  if(CGET_ARCH MATCHES "x64")
    set(OPENVR_DIR "win64")
  else()
    set(OPENVR_DIR "win32")
  endif()
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
  if(CGET_ARCH MATCHES "x64")
    set(OPENVR_DIR "linux64")
  else()
    message(FATAL_ERROR "OpenVR for Linux doesn't have ${CGET_ARCH} support")
  endif()  
else()
    message(FATAL_ERROR "OpenVR for doesn't have ${CMAKE_SYSTEM_NAME} ${CGET_ARCH} support")
endif()

if(OPENVR_DIR)
  file(GLOB OPENVR_DLLS "${CGET_openvr_REPO_DIR}/bin/${OPENVR_DIR}/*")   
  file(GLOB OPENVR_LIBS "${CGET_openvr_REPO_DIR}/lib/${OPENVR_DIR}/*")                

  file(COPY ${OPENVR_DLLS} DESTINATION "${CGET_INSTALL_DIR}/bin")
  file(COPY ${OPENVR_LIBS} DESTINATION "${CGET_INSTALL_DIR}/lib")
endif()

file(GLOB OPENVR_HEADERS "${CGET_openvr_REPO_DIR}/headers/*")               
file(COPY ${OPENVR_HEADERS} DESTINATION "${CGET_INSTALL_DIR}/include")

set(ARGS_NO_FIND_PACKAGE OFF)
